# Generated by Django 6.0.1 on 2026-01-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pays', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('rue', models.CharField(max_length=255)),
            ],
        ),
    ]
