# Generated by Django 6.0.1 on 2026-02-13 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_activate',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
